baseURL = "/"
languageCode = "en-us"
title = "Yet Another SysAdmin Website"
description = "The personal space of yet another sysadmin"
enableRobotsTXT = true
enableGitInfo = false
rssLimit = 16

[frontmatter]
date = ['date', 'lastmod']
lastmod = ['lastmod', 'date']
publishDate = ['date', 'lastmod']

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
tabWidth = 2

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[pagination]
pagerSize = 32

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
copyright = "Julien (Adyxax) Dessaux"
github_repo = "https://git.adyxax.org/adyxax/www"

[taxonomies]
tag = "tags"
